export type ArcadeItem = {
  id: string; title: string; category: string; tag: string; color: string; summary: string;
  description: string; runtime?: "builder" | "society"; available: string; limit: string;
  question: string; protocol: string[]; objective: string;
};
export const categories = ["Build & Repair", "Play & Solve", "Collaborate & Evolve"];
export const arcadeItems: ArcadeItem[] = [
  { id: "game-forge", title: "Game Forge", category: categories[0], tag: "Build", color: "#ff806b", summary: "An agent builds. Another tests.", description: "Give agents a game brief and a workspace to build in. Follow their actions, then inspect the result.", runtime: "builder", available: "Workspace preset", limit: "Uses the existing Builder runtime. Embedded gameplay preview and automatic game tests are not implemented yet.", question: "Does a builder-and-tester team produce a better game than one agent under the same budget?", protocol: ["Specify a small browser game and its acceptance checks.", "Compare one agent with a two-agent team under a shared budget.", "Inspect the produced files and verify controls manually. Do not treat a finish claim as a passing test."], objective: "Build a small browser-based maze game in the workspace. Include movement, collision handling, an exit, and a restart button. Write and run tests where possible. Explain how the operator can run it and list any checks not performed." },
  { id: "repair-bay", title: "Repair Bay", category: categories[0], tag: "Repair", color: "#afa3fa", summary: "Break it. Diagnose it. Fix it.", description: "Start with a broken project and study the route from a failure to a verified repair.", runtime: "builder", available: "Workspace preset", limit: "Uses Builder. Supply project files in the local workspace. Fault injection and automatic verification are not built in.", question: "Which repair strategy resolves the fault without introducing a regression?", protocol: ["Place a reproducible broken project in the agent workspace.", "Record the failing check before asking agents to repair it.", "Run the same checks after the repair and inspect unrelated behavior for regressions."], objective: "Inspect the project supplied by the operator in the workspace. Reproduce its failure, make a focused repair, and run the relevant tests. If no project has been supplied, request it rather than inventing a test result." },
  { id: "game-runner", title: "Game Runner", category: categories[1], tag: "Play", color: "#67d6c5", summary: "A new attempt. A better strategy?", description: "Watch agents navigate a game through restricted observations and controls.", available: "Planned environment", limit: "The game engine and restricted action adapter are not implemented. This is an example protocol, not a playable demo.", question: "Does persistent memory improve success across repeated attempts?", protocol: ["Use the same maze seeds and action budget in both conditions.", "Give one condition a persistent notebook and reset memory in the other.", "Measure completion, illegal moves and wasted steps using the game engine, not agent self-report."], objective: "Navigate a hidden maze using only engine-provided observations and legal movement actions." },
  { id: "escape-room", title: "Escape Room", category: categories[1], tag: "Solve", color: "#f3c862", summary: "Different clues. One way out.", description: "Each agent holds part of the puzzle. Study how information travels through the team.", available: "Planned environment", limit: "The puzzle engine, private clue delivery and solution evaluator are not implemented yet.", question: "How much communication does a team need to combine distributed clues?", protocol: ["Assign each agent a different, non-overlapping clue set.", "Compare unrestricted communication against a fixed message budget.", "Measure verified solutions and messages used; keep the final answer hidden from all agents."], objective: "Combine distributed clues to solve an escape-room puzzle within a fixed message budget." },
  { id: "tiny-civilization", title: "Tiny Civilization", category: categories[2], tag: "Society", color: "#c0de6f", summary: "Shared resources. Emergent choices.", description: "Observe a small group managing one scarce world, exchanging resources and proposing agreements.", runtime: "society", available: "Society preset", limit: "Uses the existing Society runtime and resource counters. The illustrated settlement is concept art, not a live simulation. Metrics remain exploratory proxies.", question: "Does open communication improve shared resource use under scarcity?", protocol: ["Choose three to eight agents and record their initial resources.", "Use the same budget and environment configuration for each comparison.", "Inspect actual transfers and resource outcomes separately from stated intentions or declared institutions."], objective: "Explore the shared world and its resource constraints. Choose whether to gather, contribute, exchange or establish agreements. Record commitments and distinguish proposed agreements from ones others actually follow." },
  { id: "relay-studio", title: "Relay Studio", category: categories[2], tag: "Handoff", color: "#ffad70", summary: "Pass the work. Keep the intent.", description: "Agents inherit unfinished projects. Investigate what survives a handoff and what gets lost.", available: "Planned environment", limit: "Automatic workspace handoffs, agent replacement and matched-condition evaluation are not implemented.", question: "Does a structured handoff reduce rework compared with full conversation history?", protocol: ["Stop work at a fixed checkpoint and preserve the same project files.", "Give the next agent either a structured handoff or the full transcript.", "Compare requirements retained, rework and final verified quality."], objective: "Continue an unfinished project from its files and the assigned handoff context." },
];
